ENT.Base = "base_entity"
ENT.Type = "anim"
ENT.PrintName 	= "Doncombine"
ENT.Author 		= "Spaaz (with credit to Faaafv)"
ENT.Contact 	= ""
ENT.Information	= ""
ENT.Category	= "Combine"
ENT.Spawnable = false
ENT.AdminSpawnable = true
